import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <link rel="icon" type="image/x-icon" href="faviconsf.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        

        {/* <!-- Primary Meta Tags --> */}
<title>SauloVinicius - Front End Developer Portfolio</title>
<meta name="title" content="SauloVinicius - Front End Developer Portfolio" />
<meta name="description" content="Professional portfolio from Saulo Vinicius.
Front End | ReactJS | NextJS | Vitejs | TypeScript | Tailwind | JavaScript | NodeJs | HTML5 | CSS | Bootstrap" />

{/* <!-- Open Graph / Facebook --> */}
<meta property="og:type" content="website" />
<meta property="og:url" content="https://metatags.io/" />
<meta property="og:title" content="SauloVinicius - Front End Developer Portfolio" />
<meta property="og:description" content="Professional portfolio from Saulo Vinicius.
Front End | ReactJS | NextJS | Vitejs | TypeScript | Tailwind | JavaScript | NodeJs | HTML5 | CSS | Bootstrap" />
<meta property="og:image" content="https://64.media.tumblr.com/94bc320a616a4e63a4868a3126cfbaac/42ac2c08a370fdc3-ea/s540x810/cc758cfe53027cb69422ca0b2fa79b56caadc15e.pnj" />

{/* <!-- Twitter --> */}
<meta property="twitter:card" content="summary_large_image" />
<meta property="twitter:url" content="https://metatags.io/" />
<meta property="twitter:title" content="SauloVinicius - Front End Developer Portfolio" />
<meta property="twitter:description" content="Professional portfolio from Saulo Vinicius.
Front End | ReactJS | NextJS | Vitejs | TypeScript | Tailwind | JavaScript | NodeJs | HTML5 | CSS | Bootstrap" />
<meta property="twitter:image" content="https://64.media.tumblr.com/94bc320a616a4e63a4868a3126cfbaac/42ac2c08a370fdc3-ea/s540x810/cc758cfe53027cb69422ca0b2fa79b56caadc15e.pnj" />

{/* <!-- Meta Tags Generated with https://metatags.io --> */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
